#logging:
#  level:
#    ROOT: DEBUG
#    tech.jhipster: DEBUG
#    org.hibernate.SQL: DEBUG

spring:
  application:
    name: pattern-dto
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/patterndto;DB_CLOSE_DELAY=-1
    username: patterndto
    password:
    hikari:
      poolName: Hikari
      auto-commit: true

  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: true

jhipster:
  clientApp:
    name: 'patterndtoApp'





